CREATE DATABASE ECOMMERCE_DB; 
 
 USE ECOMMERCE_DB;
 
 CREATE TABLE CLIENTES (
 IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
 NOME VARCHAR(100) NOT NULL,
 EMAIL VARCHAR(254)NOT NULL UNIQUE,
 TIPO ENUM('PESSOA_FÍSICA', 'PESSOA_JURIDICA')NOT NULL,
 CPF VARCHAR(11) NULL UNIQUE,
 CNPJ VARCHAR(14) NULL UNIQUE,
 RAZAO_SOCIAL VARCHAR(100) NULL,
 DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT TIPO_CHECK CHECK (
   (TIPO = 'PESSOA_FÍSICA' AND NOME IS NOT NULL AND CPF IS NOT NULL AND RAZAO_SOCIAL IS NULL AND CNPJ IS NULL) OR 
   (TIPO = 'PESSOA_JURIDICA' AND RAZAO_SOCIAL IS NOT NULL AND CNPJ IS NOT NULL AND CPF IS NULL)
 ),
 CONSTRAINT EMAIL_VALIDO_CHECK CHECK (
 EMAIL REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'
 )
 );
 
 
 CREATE TABLE ENDERECOS (
 IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
 ID_CLIENTE INT NOT NULL,
 TIPO ENUM('RESIDENCIAL', 'COMERCIAL') NOT NULL,
 LOGRADOURO VARCHAR(100) NOT NULL,
 NUMERO VARCHAR(10) NOT NULL,
 COMPLEMENTO VARCHAR(50) NULL, 
 BAIRRO VARCHAR(50) NOT NULL,
 CIDADE VARCHAR(50) NOT NULL,
 ESTADO CHAR(2) NOT NULL,
 CEP CHAR(8) NOT NULL,
 
 CONSTRAINT FK_CLIENTES_ENDERECOS 
 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(IDCLIENTE)
 );
 
 
 CREATE TABLE TELEFONES (
 IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
 ID_CLIENTE INT NOT NULL,
 TIPO ENUM('CELULAR', 'COMERCIAL', 'RESIDENCIAL') NOT NULL,
 NUMERO VARCHAR(20) NOT NULL,
 
 CONSTRAINT FK_CLIENTES_TELEFONES
 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(IDCLIENTE) ON DELETE CASCADE
 );
 
 
 
 CREATE TABLE CATEGORIAS (
 IDCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
 NOME_CATEGORIA VARCHAR(50) NOT NULL UNIQUE,
 DESCRICAO VARCHAR(255) NULL
 );
 
 CREATE TABLE FORNECEDORES (
 IDFORNECEDOR INT PRIMARY KEY AUTO_INCREMENT,
 NOME_FORNECEDOR VARCHAR(100) NOT NULL,
 CNPJ VARCHAR(14) NOT NULL UNIQUE,
 EMAIL VARCHAR(254) NOT NULL UNIQUE,
 TELEFONE VARCHAR(20) NOT NULL 
 );
 
 
 CREATE TABLE PRODUTOS (
 IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
 NOME_PRODUTO VARCHAR(50) NOT NULL UNIQUE,
 ID_CATEGORIA INT,
 DESCRICAO VARCHAR(255)NULL,
 PRECO_UNITARIO DECIMAL(10,2) NOT NULL,  
 QUANTIDADE_ESTOQUE INT DEFAULT 0, 
 ID_FORNECEDOR INT,
 DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
 
 CONSTRAINT  PRECO_POSITIVO_CHECK  CHECK 
 (PRECO_UNITARIO > 0), 
 
 CONSTRAINT FK_CATEGORIAS_PRODUTOS
 FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(IDCATEGORIA),
 
 CONSTRAINT FK_FORNECEDORES_PRODUTOS
 FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(IDFORNECEDOR)
 );
 
 
 
 CREATE TABLE PEDIDOS (
 IDPEDIDO INT PRIMARY KEY AUTO_INCREMENT,
 ID_CLIENTE INT NOT NULL, 
 VALOR_TOTAL DECIMAL(10,2) NOT NULL,
 DATA_PEDIDO DATETIME DEFAULT CURRENT_TIMESTAMP,
 STATUS ENUM('PENDENTE', 'PAGO', 'CANCELADO') DEFAULT 'PENDENTE',  
 
 CONSTRAINT FK_CLIENTE_PEDIDOS
 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(IDCLIENTE) ON DELETE CASCADE
 );
 
 
 CREATE TABLE ITENS_PEDIDOS (
 IDITEM INT PRIMARY KEY AUTO_INCREMENT,
 ID_PEDIDO INT NOT NULL,
 ID_PRODUTO INT NOT NULL, 
 PRECO_UNITARIO DECIMAL(10,2) NOT NULL,
 QUANTIDADE INT NOT NULL CHECK (QUANTIDADE > 0), 
 SUBTOTAL DECIMAL(10,2) GENERATED ALWAYS AS (PRECO_UNITARIO * QUANTIDADE) STORED, 
 
 CONSTRAINT FK_PEDIDO_ITENS 
 FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(IDPEDIDO),
 
 CONSTRAINT FK_PRODUTO_ITENS
 FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(IDPRODUTO)
 ); 
 
 
 
 CREATE TABLE PAGAMENTOS (
 IDPAGAMENTO INT PRIMARY KEY AUTO_INCREMENT,
 ID_PEDIDO INT NOT NULL,
 VALOR_PAGO DECIMAL(10,2) NOT NULL,
 METODO ENUM('CARTÃO', 'BOLETO', 'PIX') NOT NULL,
 STATUS ENUM('APROVADO', 'RECUSADO', 'PENDENTE') NOT NULL,
 DATA_PAGAMENTO DATETIME DEFAULT CURRENT_TIMESTAMP,
 
 CONSTRAINT FK_PEDIDOS_PAGAMENTOS 
 FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(IDPEDIDO)
 );
 
 
 CREATE TABLE ENTREGAS (
 IDENTREGA INT PRIMARY KEY AUTO_INCREMENT,
 ID_PEDIDO INT NOT NULL,
 ID_ENDERECO INT NOT NULL,
 TRANSPORTADORA VARCHAR(50) NOT NULL,
 DATA_ENVIO DATE NULL,
 DATA_PREVISTA DATE NULL,
 CODIGO_RASTREAMENTO VARCHAR(20) NOT NULL,
 STATUS ENUM('PREPARAÇÃO', 'ENVIADO','EM_TRANSITO', 'ENTREGUE', 'CANCELADO') NOT NULL,
 DATA_ENTREGA DATE NULL,
 
 CONSTRAINT FK_PEDIDOS_ENTREGAS
 FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(IDPEDIDO),
 
 CONSTRAINT FK_ENDERECOS_ENTREGAS
 FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECOS(IDENDERECO)
 ); 
 
 CREATE TABLE AVALIACOES (
 IDAVALIACAO INT PRIMARY KEY AUTO_INCREMENT,
 ID_CLIENTE INT NOT NULL,
 ID_PRODUTO INT NOT NULL,
 NOTA TINYINT NOT NULL CHECK (NOTA BETWEEN 1 AND 5), 
 COMENTARIO VARCHAR(255) NULL, 
 DATA_AVALIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
 
 CONSTRAINT FK_CLIENTES_AVALIACOES 
 FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(IDCLIENTE),
 
 CONSTRAINT FK_PRODUTOS_AVALIACOES
 FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(IDPRODUTO)
 );
